# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
