# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0005_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 22, 37, 59, 913535, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
