# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0006_template_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 20, 16, 38, 48, 340931, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='key',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='meta_data',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
